### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'Model'. Did you mean: 'models'?

### ISSUE THREAD

**Issue by Sourish0911** [amitport/EDEN-Distributed-Mean-Estimation#1]
I am trying to reproduce the experiment at my end.
I am using the TensorFlow implementation.
On running the trainer.py file I am getting the error as mentioned in the title of the issue.
Please see below

 2023-08-24 23:00:46.600033: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-24 23:00:46.623500: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-24 23:00:46.974261: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/sourish-wicon-lab/fedlen/EDEN-Distributed-Mean-Estimation/tf/trainer.py", line 7, in <module>
    import fed_avg_schedule
  File "/home/sourish-wicon-lab/fedlen/EDEN-Distributed-Mean-Estimation/tf/fed_avg_schedule.py", line 37, in <module>
    ModelBuilder = Callable[[], tff.learning.Model]
AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'Model'. Did you mean: 'models'?

I have checked the documentation of tensorflow_federated and found that tensorflow_federated.python.learning has module named models instead of Model
Please help me clarify what I am doing wrong?

**Comment by amitport** [comment]
Hi, can you specify the versions you use (especially, python, tff, tf related packages)?

**Comment by Sourish0911** [comment]
Hi,
Please find the version below 
tensorboard==2.12.3
tensorboard-data-server==0.7.1
tensorflow==2.12.1
tensorflow-compression==2.12.0
tensorflow-datasets==4.9.2
tensorflow-estimator==2.12.0
tensorflow-federated==0.61.0
tensorflow-io-gcs-filesystem==0.33.0
tensorflow-metadata==1.14.0
tensorflow-model-optimization==0.7.3
tensorflow-privacy==0.8.10
tensorflow-probability==0.20.1
termcolor==2.3.0
testresources==2.0.1
testscenarios==0.5.0
testtools==2.5.0
tf-estimator-nightly==2.14.0.dev2023080308
tf-nightly==2.14.0.dev20230603
tfa-nightly==0.16.0.dev20220215164019
Python version -->
Python 3.10.12

**Comment by amitport** [comment]
@Sourish0911, your versions are not the ones from tf/requirements.txt, and these packages often introduce breaking changes, even in minor versions. In any case, I will try to update the code to the latest versions. 

Also, note that EDEN is also implemented in openFL:
https://github.com/securefederatedai/openfl/pull/527

**Comment by Sourish0911** [comment]
@amitport I have used these version as some of them are no longer being supported.
Since dependency issues are dominant, updating the code to the latest version would be of great help.

Thanks for the kind consideration 

Will check out the implementation in openFL
Thanks again

**Comment by amitport** [comment]
I will update to the latest stable version, but it will take some time considering the many breaking changes in `tensorflow federated`. If you're looking for the core tensorflow implementation, this is in https://github.com/amitport/EDEN-Distributed-Mean-Estimation/blob/master/tf/eden.py#L177 and should work on recent tensorflow versions.

**Comment by Sourish0911** [comment]
Thanks for your kind suggestion. I will close the issue from end.
